In [1]:
!pip install tensorflow

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/93/21/9b035a4f823d6aee2917c75415be9a95861ff3d73a0a65e48edbf210cec1/tensorflow-2.15.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for tensorflow-intel==2.15.0 from https://files.pythonhosted.org/packages/4c/48/1a5a15517f18eaa4ff8d598b1c000300b20c1bb0e624539d702117a0c369/tensorflow_intel-2.15.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/a2/ad/e0d3c824784ff121c03cc031f944bc7e139a8f1870ffd2845cc2dd76f6c4/absl_py-2.1.0-py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>=23.5.26 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata
  Obtaining dependency information for gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 from https://files.pythonhosted.org/packages/fa

   --------------------------------- ------ 252.0/300.9 MB 3.9 MB/s eta 0:00:13
   --------------------------------- ------ 252.2/300.9 MB 3.9 MB/s eta 0:00:13
   --------------------------------- ------ 252.4/300.9 MB 3.9 MB/s eta 0:00:13
   --------------------------------- ------ 252.5/300.9 MB 3.9 MB/s eta 0:00:13
   --------------------------------- ------ 252.7/300.9 MB 3.9 MB/s eta 0:00:13
   --------------------------------- ------ 252.8/300.9 MB 3.9 MB/s eta 0:00:13
   --------------------------------- ------ 253.0/300.9 MB 3.9 MB/s eta 0:00:13
   --------------------------------- ------ 253.2/300.9 MB 3.9 MB/s eta 0:00:13
   --------------------------------- ------ 253.3/300.9 MB 3.9 MB/s eta 0:00:13
   --------------------------------- ------ 253.5/300.9 MB 3.9 MB/s eta 0:00:13
   --------------------------------- ------ 253.7/300.9 MB 3.9 MB/s eta 0:00:13
   --------------------------------- ------ 253.8/300.9 MB 3.9 MB/s eta 0:00:13
   --------------------------------- ---

In [5]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#Assuming 10 features as IP and 5 as OP
input_dim=10
output_dim=5

#Define a simple neural network with 1 IP layer, 1 hidden layer and 1 OP layer
model = Sequential([Dense(64, activation ='relu', input_shape=(input_dim,)),
                   Dense(32, activation ='relu'),
                   Dense(output_dim, activation ='softmax')])
#Dense-how each neuron is densely connected to all neurons in the previous layer.
#Unit(here,64,32,.)specifies the number of neurons in the layer.

#Compile the model with appropriate loss function and optimizer
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()    

#This will print out the model and show the no. of architecture and parameters



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 64)                704       
                                                                 
 dense_2 (Dense)             (None, 32)                2080      
                                                                 
 dense_3 (Dense)             (None, 5)                 165       
                                                                 
Total params: 2949 (11.52 KB)
Trainable params: 2949 (11.52 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

#Generate some example data
X_train = np.random.random((100, 20))
Y_train = np.random.randint(2, size=(100,1))

print("X-data", X_train)
print("Y-data", Y_train)

X-data [[0.99424219 0.67584704 0.68448119 ... 0.74531224 0.01023698 0.31306771]
 [0.59450338 0.31585192 0.22452986 ... 0.0587392  0.73101114 0.91644532]
 [0.91002874 0.76427801 0.67478588 ... 0.84680144 0.67284867 0.33787701]
 ...
 [0.04466701 0.32862329 0.80735563 ... 0.54605216 0.52734905 0.95168424]
 [0.56649724 0.58128964 0.53221741 ... 0.48578268 0.24519295 0.25698673]
 [0.08533336 0.5004066  0.51779942 ... 0.45391055 0.02292394 0.97918421]]
Y-data [[1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]]


In [17]:
#Define a simple neural network model 
#This Artificial neural network (ANN) will study the avove data, and recognise complex patterns in them and make decisions
#The more you make the machine train, the more the machine understands.
model = Sequential()
model.add(Dense(64, activation ='relu', input_dim=20))
model.add(Dense(32, activation ='relu'))
model.add(Dense(1, activation ='sigmoid'))

#Compile the model with appropriate loss function and optimizer
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

#Train the model
model.fit(X_train, Y_train, epochs=1, batch_size=32)
#During an epoch, the model processes every example in the training dataset once, both
# in the forward pass and the backward pass

 

4/4 [==============================] - 1s 5ms/step - loss: 0.7119 - accuracy: 0.5000


In [18]:
model.fit(X_train, Y_train, epochs=10, batch_size=32)

Epoch 1/10
4/4 [==============================] - 0s 3ms/step - loss: 0.6950 - accuracy: 0.5600
Epoch 2/10
4/4 [==============================] - 0s 0s/step - loss: 0.6865 - accuracy: 0.5800
Epoch 3/10
4/4 [==============================] - 0s 0s/step - loss: 0.6823 - accuracy: 0.5500
Epoch 4/10
4/4 [==============================] - 0s 1ms/step - loss: 0.6775 - accuracy: 0.6100
Epoch 5/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6734 - accuracy: 0.6300
Epoch 6/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6724 - accuracy: 0.6500
Epoch 7/10
4/4 [==============================] - 0s 0s/step - loss: 0.6689 - accuracy: 0.6700
Epoch 8/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6650 - accuracy: 0.6500
Epoch 9/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6618 - accuracy: 0.6500
Epoch 10/10
4/4 [==============================] - 0s 3ms/step - loss: 0.6597 - accuracy: 0.6000


In [19]:
model.fit(X_train, Y_train, epochs=20, batch_size=32)

Epoch 1/20
4/4 [==============================] - 0s 197us/step - loss: 0.6563 - accuracy: 0.6400
Epoch 2/20
4/4 [==============================] - 0s 6ms/step - loss: 0.6538 - accuracy: 0.6500
Epoch 3/20
4/4 [==============================] - 0s 5ms/step - loss: 0.6519 - accuracy: 0.6600
Epoch 4/20
4/4 [==============================] - 0s 0s/step - loss: 0.6506 - accuracy: 0.6400
Epoch 5/20
4/4 [==============================] - 0s 0s/step - loss: 0.6481 - accuracy: 0.6700
Epoch 6/20
4/4 [==============================] - 0s 1ms/step - loss: 0.6469 - accuracy: 0.6800
Epoch 7/20
4/4 [==============================] - 0s 5ms/step - loss: 0.6444 - accuracy: 0.6800
Epoch 8/20
4/4 [==============================] - 0s 5ms/step - loss: 0.6402 - accuracy: 0.6800
Epoch 9/20
4/4 [==============================] - 0s 0s/step - loss: 0.6380 - accuracy: 0.7100
Epoch 10/20
4/4 [==============================] - 0s 0s/step - loss: 0.6390 - accuracy: 0.6200
Epoch 11/20
4/4 [========================

In [20]:
#Epochs is the no. of times you want the machine to train. The more it is, the accuracy will increase.

In [22]:
#Using Keras for image classification
from keras.datasets import mnist
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D, Flatten, Dense

#Load the MNIST dataset
(X_train, Y_train),(X_test,Y_test)=mnist.load_data()

#Preprocess the data
X_train=X_train.reshape(-1,28,28,1)/255.0
X_test=X_test.reshape(-1,28,28,1)/255.0
Y_train=to_categorical(Y_train, num_classes=10)
Y_test=to_categorical(Y_test, num_classes=10)

#Create a Convulational Neural Network (CNN) model
model = Sequential()
model.add(Conv2D(32, kernel_size=(3,3), activation ='relu', input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))  #Reducing the computation.to reduce the size of feature maps, 
#which in turn makes computation faster because the number of training parameters is reduced
model.add(Flatten())
model.add(Dense(128, activation ='relu'))
model.add(Dense(10, activation ='softmax'))

#Compile the model with appropriate loss function and optimizer
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

#Train the model
model.fit(X_train, Y_train, epochs=5, batch_size=32, validation_data=(X_test,Y_test))



Epoch 1/5
1875/1875 [==============================] - 26s 13ms/step - loss: 0.1491 - accuracy: 0.9554 - val_loss: 0.0555 - val_accuracy: 0.9808
Epoch 2/5
1875/1875 [==============================] - 23s 12ms/step - loss: 0.0496 - accuracy: 0.9847 - val_loss: 0.0465 - val_accuracy: 0.9849
Epoch 3/5
1875/1875 [==============================] - 24s 13ms/step - loss: 0.0317 - accuracy: 0.9901 - val_loss: 0.0468 - val_accuracy: 0.9851
Epoch 4/5
1875/1875 [==============================] - 23s 13ms/step - loss: 0.0212 - accuracy: 0.9930 - val_loss: 0.0424 - val_accuracy: 0.9870
Epoch 5/5
1875/1875 [==============================] - 24s 13ms/step - loss: 0.0139 - accuracy: 0.9958 - val_loss: 0.0408 - val_accuracy: 0.9858
